Add User Settings
dollarshaveclub/acyl pull request #112
Opened 2020-08-28 00:53 UTC by esterlinej

### User Settings
- Implement a user view in the UI, for user-specific settings/info
- The initial view should be barebones with little or no added functionality. Maybe just a “logout” button that invalidates the session.

-------------------------------------------------------------------------

### Details
- Regarding the user view: pretty much every authenticated web UI has a view/page for user or account settings. Edit profile, change password, log out, etc. 
- Usually symbolized with an icon similar to https://fontawesome.com/icons/user?style=solid
- in most cases (including DSC) the user settings icon is put in the upper right hand corner of the UI
- the complication for Acyl UI is that location (upper right corner) is where the DQA link is (at least for the status page)
- so we need to come up with a location for the "user settings" icon that doesn't conflict and makes intuitive sense
- in terms of the contents of the user setting view, for now probably just a logout link/button is sufficient just as a placeholder (this would invalidate the session)

2020-09-11 19:43 UTC, esterlinej commented
<img width="244" alt="user-settings" src="https://user-images.githubusercontent.com/231105/92966430-634dc180-f42c-11ea-93da-34c9d3a2241c.png">

2020-09-11 20:10 UTC, bkeroackdsc requested changes

2020-09-11 20:10 UTC, bkeroackdsc commented on pkg/api/api_ui.go
> +	"user": path.Join("views", "partials", "user.html"),
I'm not sure if this needs to be a separate partial, since it will always be present in the header.

2020-09-11 20:10 UTC, bkeroackdsc commented on pkg/api/api_ui.go
> +		DisplaySettings: false,
I'm not sure what "DisplaySettings" means.

2020-09-11 20:10 UTC, bkeroackdsc commented on ui/views/partials/user.html
> +{{ define "user-settings" }}
I don't think this needs to be a separate partial, since this is only used in one spot.

2020-09-11 20:10 UTC, bkeroackdsc commented on ui/views/partials/header.html
> +                {{ if .DisplaySettings }}
Since every view is authenticated, I don't think we need this boolean.

2020-09-11 20:10 UTC, bkeroackdsc commented on ui/assets/user.js
> +    req.open('GET', `${apiBaseURL}/v2/user/settings`, true);
The user information is part of the session, so you can use server-side templating to insert this data (we do that elsewhere for GitHub user name) instead of AJAX.

2020-09-11 20:14 UTC, mikeykhalil commented on ui/assets/user.js
> +    if (userSettingsGroup === null) {
Since the `===` is being used here, i think `userSettingsGroup` could be undefined  and this expression would evaluate to false. 

2 possible alternatives:
1. `if (userSettingsGroup == null)` // no type equality check
2. `if (!userSettingsGroup)` // let javascripts truthy/falsy logic handle it

2020-09-11 20:46 UTC, esterlinej commented on pkg/api/api_ui.go
> +		DisplaySettings: false,
This is to display the user settings on the page, gating which pages display the settings dropdown.

2020-09-11 20:47 UTC, esterlinej commented on ui/views/partials/header.html
> +                {{ if .DisplaySettings }}
Sure, though we discussed that the error pages shouldn't display the user settings, we need a way to gate this.

2020-09-11 20:47 UTC, bkeroackdsc commented on ui/assets/user.js
> +    req.open('GET', `${apiBaseURL}/v2/user/settings`, true);
For example:
https://github.com/dollarshaveclub/acyl/blob/bc372c67572dd4d8ea7d41c05ff00ce081082b88/ui/views/home.html#L48

2020-09-11 23:57 UTC, esterlinej commented on ui/assets/user.js
> +    req.open('GET', `${apiBaseURL}/v2/user/settings`, true);
Okay, the only issue is that we don't have the session for Status page, so we'll need to update that to work

2020-09-21 19:07 UTC, esterlinej commented on pkg/api/api_ui.go
> +				uis.Authenticated = true
We may want to add an optional toggle `DummySessionAuthenticated` to control this from the mockui, but for now it's set to true.

2020-09-21 20:48 UTC, bkeroackdsc requested changes

2020-09-21 20:48 UTC, bkeroackdsc commented on pkg/api/api_ui.go
> +	GitHubUser    string
If this is required for every view, it should be in the base template data.

2020-09-21 20:48 UTC, bkeroackdsc commented on pkg/api/api_ui.go
> +		RenderUserSettings: false,
This should probably default to true.

2020-09-21 20:48 UTC, bkeroackdsc commented on pkg/api/api_ui.go
>  func (api *uiapi) defaultBaseTemplateData() BaseTemplateData {
This could take a ui session and then set the GitHub user field.

2020-09-21 20:48 UTC, bkeroackdsc commented on pkg/api/api_ui.go
> +	RenderUserSettings bool
Since GitHub user is needed for user settings, that field should be here.

2020-09-21 21:50 UTC, esterlinej commented on pkg/api/api_ui.go
> +		RenderUserSettings: false,
If we're passing uis to this function, then we can set to true if the user isn't empyt/blank

2020-09-21 22:50 UTC, bkeroackdsc requested changes

2020-09-21 22:50 UTC, bkeroackdsc commented on pkg/api/api_ui.go
> +func (api *uiapi) defaultBaseTemplateData(session *models.UISession) BaseTemplateData {
If you want to pass in a pointer, check for nil prior to using it.

2020-09-21 22:50 UTC, bkeroackdsc commented on pkg/api/api_ui.go
> +	}
You can move this up to the literal (only if you guarantee that session isn't nil):

```
   GitHubUser: session.GitHubUser,
   RenderUserSettings: session.GitHubUser != "",
```

2020-09-21 22:50 UTC, bkeroackdsc commented on pkg/api/api_ui.go
> +	if err := api.views["auth_error"].Execute(&b, api.defaultBaseTemplateData(&models.UISession{})); err != nil {
If `defaultBaseTemplateData()` was changed to handle a nil session, you could avoid unnecessarily allocating a new struct here.

2020-09-21 22:50 UTC, bkeroackdsc commented on pkg/api/api_ui.go
> +		api.render(w, "auth_error", api.defaultBaseTemplateData(&models.UISession{}))
Pass nil if you fix the method to handle it properly.

2020-09-21 22:50 UTC, bkeroackdsc commented on pkg/api/api_ui.go
> +	api.render(w, "denied", api.defaultBaseTemplateData(&models.UISession{}))
Same here.

2020-09-21 23:33 UTC, bkeroackdsc approved these changes

2020-09-21 23:40 UTC, merged