Create unknown status prior to actions
dollarshaveclub/acyl pull request #118
Opened 2020-09-15 00:10 UTC by esterlinej

2020-09-15 23:32 UTC, mikeykhalil commented on pkg/eventlogger/status_test.go
> +func TestSetNewStatusUnknown(t *testing.T) {
Think I misunderstood which package this test was located in and the full contents of the tests when reading it in Slack.

I'm not sure if this test alone does enough to prevent a regression of this issue or ensure it has been fixed. 

Don't have the code on hand at the moment, but perhaps we can validate the event log status in an API handler test or in the environment creation test?

2020-09-16 00:46 UTC, esterlinej commented on pkg/eventlogger/status_test.go
> +func TestSetNewStatusUnknown(t *testing.T) {
I added a secondary test for env_test, hopefully the combination of both tests will catch any regression

2020-09-16 18:53 UTC, mikeykhalil requested changes

2020-09-16 18:53 UTC, mikeykhalil commented on pkg/nitro/env/env_test.go
> +	env, err := m.generateNewEnv(context.Background(), &rrd)
What if we call `m.create` here to better mimic what would happen in the API handler and to test out multiple calls to `SetNewStatus`?

For instance, I think the behavior that this PR changes is that it calls `SetNewStatus` almost immediately within the handler, and then it's called again in functions like `m.create`. So we should want this test to basically verify that

1. The event log is able to be set to an unknown event status initially
2. The event log status gets updated to `DoneStatus` after m.create finishes.

2020-09-17 00:48 UTC, esterlinej commented
<img width="1139" alt="Screen Shot 2020-09-16 at 5 43 25 PM" src="https://user-images.githubusercontent.com/231105/93406548-c5e7f880-f844-11ea-96c1-977eb4fb1487.png">

2020-09-17 21:03 UTC, mikeykhalil commented on pkg/nitro/env/env_test.go
> +	if err != nil {
I think we can get rid of lots of these validations, since `TestCreate` performs these same validations. 

What we need to verify here is that the event log status gets updated after the call to `create`. I believe this can be retrieved by calling `dl. GetEventStatus`

2020-09-17 21:04 UTC, esterlinej commented on pkg/nitro/env/env_test.go
> +	if err != nil {
Simple enough, will update

2020-09-17 21:07 UTC, mikeykhalil commented on pkg/nitro/env/env_test.go
> +	//cir := map[string]error{
if not needed, perhaps we can just delete this?

2020-09-17 21:09 UTC, esterlinej commented on pkg/nitro/env/env_test.go
> +	//cir := map[string]error{
Yeah, meant to do that

2020-09-17 21:28 UTC, mikeykhalil approved these changes

2020-09-17 21:40 UTC, bkeroackdsc approved these changes

2020-09-17 21:50 UTC, merged