fix: issue 116, create safeguards to release lock
dollarshaveclub/acyl pull request #119
Opened 2020-09-15 01:22 UTC by mikeykhalil

* This introduces a couple new fields to change the behavior of a `LockProvider`: a `ForcePreemption` field and a `ForceUnlock` field. Since we introduced some more fields, I thought it made sense to simplify to a single LockProvider factory method so that we have a single method to update and set default values for a `LockProviderConfig`

2020-09-15 23:34 UTC, bkeroackdsc requested changes

2020-09-15 23:34 UTC, bkeroackdsc commented on pkg/locker/locker.go
> +func WithForceUnlock(duration time.Duration) LockProviderOption {
A better name would be "UnlockTimeout" or "MaximumLockDuration".

2020-09-15 23:34 UTC, bkeroackdsc commented on pkg/locker/locker.go
> +func WithForcePreemption(duration time.Duration) LockProviderOption {
"PreemptionTimeout" is a better name for this.

2020-09-15 23:34 UTC, bkeroackdsc commented on pkg/locker/locker.go
> +func WithLockWait(lockWait time.Duration) LockProviderOption {
"LockTimeout" is a better name.

2020-09-15 23:34 UTC, bkeroackdsc commented on cmd/integration.go
> +	plf, err := locker.NewPreemptiveLockerFactory(lp)
If these always follow each other (`locker.NewLockProvider()` followed by `locker.NewPreemptiveLockerFactory()`) then you should combine them into a single function.

2020-09-15 23:34 UTC, bkeroackdsc commented on pkg/locker/fake_lock.go
> +	lock.Unlock(context.Background())
If I'm understanding this correctly, this should probably be a `select` with one case that sends on `lock.preempt` and another that waits on a timer that does the forced unlock once the forcePreemption duration is elapsed.

2020-09-15 23:34 UTC, bkeroackdsc commented on pkg/locker/fake_lock.go
> +	}()
This seems incorrect. It will always stay alive for the full force unlock duration, while it should return when the lock is otherwise preempted or unlocked normally.

2020-09-15 23:34 UTC, bkeroackdsc commented on pkg/locker/locker.go
> +		config.enableTracing = enableTracing
Possibly redundant. A non-empty APM service name implies tracing should be enabled.

2020-09-15 23:34 UTC, bkeroackdsc commented on pkg/locker/locker.go
> +)
When implementing enums, the first value should almost always be "Unknown"/unset to indicate the zero value.

2020-09-15 23:34 UTC, bkeroackdsc commented on pkg/locker/postgres_lock.go
> +	pl.Unlock(context.Background())
Same comment here as for the same function in the fake. It seems like you'd want a `select` here.

2020-09-15 23:34 UTC, bkeroackdsc commented on pkg/locker/postgres_lock.go
> +	}()
Similar issue here as the fake comment above. This goroutine should exit when the lock is normally unlocked or preempted.

2020-09-17 17:50 UTC, mikeykhalil commented on pkg/locker/locker.go
> +func WithForceUnlock(duration time.Duration) LockProviderOption {
Fixed here: https://github.com/dollarshaveclub/acyl/pull/119/commits/74e5377c4bc571c1346bdd0a28b81e7cae22c465#diff-3491d15067d4403add4736c7915432e1R26

2020-09-17 17:50 UTC, mikeykhalil commented on pkg/locker/locker.go
> +func WithForcePreemption(duration time.Duration) LockProviderOption {
Fixed here: https://github.com/dollarshaveclub/acyl/pull/119/commits/74e5377c4bc571c1346bdd0a28b81e7cae22c465#diff-3491d15067d4403add4736c7915432e1R34

2020-09-17 17:50 UTC, mikeykhalil commented on pkg/locker/locker.go
> +func WithLockWait(lockWait time.Duration) LockProviderOption {
Fixed here: https://github.com/dollarshaveclub/acyl/pull/119/commits/74e5377c4bc571c1346bdd0a28b81e7cae22c465#diff-3491d15067d4403add4736c7915432e1R44

2020-09-17 17:50 UTC, mikeykhalil commented on cmd/integration.go
> +	plf, err := locker.NewPreemptiveLockerFactory(lp)
Added 2 new helper functions, one for each kind of lock provider:

https://github.com/dollarshaveclub/acyl/pull/119/commits/74e5377c4bc571c1346bdd0a28b81e7cae22c465#diff-3491d15067d4403add4736c7915432e1R120

Little awkward because there are 2 sets of functional arguments, but I do think it simplifies things for the caller.

2020-09-17 17:51 UTC, mikeykhalil commented on pkg/locker/locker.go
> +		config.enableTracing = enableTracing
True, added that change here: https://github.com/dollarshaveclub/acyl/pull/119/commits/74e5377c4bc571c1346bdd0a28b81e7cae22c465#diff-3491d15067d4403add4736c7915432e1R102

2020-09-17 19:11 UTC, mikeykhalil commented on pkg/locker/postgres_lock.go
> +	pl.Unlock(context.Background())
I like this idea a lot and implemented it [here](https://github.com/dollarshaveclub/acyl/pull/119/commits/74e5377c4bc571c1346bdd0a28b81e7cae22c465#diff-bce65b51266068615a521ee5543292f9R210).

While this logic is sound, the way we read from this channel in `env.go` still does not guarantee that the lock will ever get unlocked. This is because we actually depend on a deferred function call from a different goroutine, that does not read from the `preempt` channel directly [here](https://github.com/dollarshaveclub/acyl/blob/master/pkg/nitro/env/env.go#L228).


I have one idea i'm going to try out though to modify how we actually use the preemptive locker in `env.go`, and will post up here when that is ready for review. 

---
As a backup plan though, I think the original logic works as this implementation of Unlock is idempotent. We would be making extraneous calls though.

2020-09-17 20:48 UTC, mikeykhalil commented on pkg/locker/postgres_lock.go
> +	pl.Unlock(context.Background())
Okay, made the change to env.go [here](https://github.com/dollarshaveclub/acyl/pull/119/files#diff-1ea1b07272feac8de974c49bbec91702R246).

Since the passed in function to `lockingOperation` can block indefinitely, I decided to add some protection to at least ensure the root goroutine ends. This way, even if the blocking operation fails, the goroutine which called `lockingOperation` is able to complete and specifically call the deferred function which unlocks the lock.

2020-09-18 00:40 UTC, mikeykhalil commented on pkg/locker/locker.go
> +)
Fixed here: https://github.com/dollarshaveclub/acyl/pull/119/files#diff-3491d15067d4403add4736c7915432e1R80

2020-09-18 00:49 UTC, mikeykhalil commented on pkg/locker/postgres_lock.go
> +	}()
Ended up removing this logic, in favor of using a [context](https://github.com/dollarshaveclub/acyl/pull/119/files#diff-bce65b51266068615a521ee5543292f9R160
) with a timeout period within the goroutine that manages `handleEvents`. In the event the context is canceled (e.g. after the maxLockDuration), it will call `handleNotification(np)`. 

Handle notifications perform this logic and will exit normally if preempted.

2020-09-18 00:51 UTC, mikeykhalil commented on pkg/locker/fake_lock.go
> +	lock.Unlock(context.Background())
Resolved by making use of the newly created [handleNotification](https://github.com/dollarshaveclub/acyl/pull/119/files#diff-e2a2c0cf8eb3d6bbeabf2693327aaa17R182) method

2020-09-18 00:52 UTC, mikeykhalil commented on pkg/locker/fake_lock.go
> +	}()
Resolved by making use of the newly created [handleNotification](https://github.com/dollarshaveclub/acyl/pull/119/files#diff-e2a2c0cf8eb3d6bbeabf2693327aaa17R182) method

2020-09-21 22:15 UTC, mikeykhalil commented on testing/localsecrets/main.go
> +	secrets["production/furan/github/token"] = getGitHubToken()
This change was required due to an update to one of the base docker images being used.

2020-09-21 23:04 UTC, bkeroackdsc commented on pkg/locker/fake_lock.go
> +	case <-time.After(fpl.conf.preemptionTimeout):
I probably would put a debug log here, something like `preemptable lock: <lock key>: preemption timeout reached, unlocking: 30m`.

2020-09-21 23:04 UTC, bkeroackdsc commented on pkg/locker/locker.go
> +		config.enableTracing = enableTracing
The point is to remove the redundant config option, not to set it automatically.

2020-09-21 23:12 UTC, bkeroackdsc approved these changes

2020-09-21 23:12 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +	}
You could create a derived context with a set timeout here as well, if you want additional assurance that the input function will be signaled to abort at some point.

However we can never guarantee that the function will respect the context, so the logic you added is a good fallback.

2020-09-21 23:16 UTC, bkeroackdsc commented on pkg/locker/fake_lock.go
> +	case <-time.After(fpl.conf.preemptionTimeout):
Not just the fake, also in the Postgres implementation.

2020-09-21 23:23 UTC, mikeykhalil commented on pkg/nitro/env/env.go
> +	}
Yeah, I think the problem is that the passed in functions don't always respect the context, so it's important for this method to make sure the context cancelation is handled properly. 

I think there are some reliable mechanisms in place that ensure the context itself will get canceled at some point, including the Manager's `OperationTimeout` and the PostgresLock's `MaxLockDuration`.

2020-09-21 23:28 UTC, esterlinej approved these changes
LGTM, but defer to Ben for greater context

2020-09-21 23:39 UTC, mikeykhalil commented on pkg/locker/fake_lock.go
> +	case <-time.After(fpl.conf.preemptionTimeout):
[Fake implementation fix](https://github.com/dollarshaveclub/acyl/pull/119/commits/0ea4fe0201e70de4d5622ab43612fe63d9c81c7d#diff-e2a2c0cf8eb3d6bbeabf2693327aaa17R188)

[Postgres implementation fix](https://github.com/dollarshaveclub/acyl/pull/119/commits/0ea4fe0201e70de4d5622ab43612fe63d9c81c7d#diff-bce65b51266068615a521ee5543292f9R214url)

2020-09-21 23:43 UTC, mikeykhalil commented on pkg/locker/locker.go
> +		config.enableTracing = enableTracing
Fixed here: https://github.com/dollarshaveclub/acyl/pull/119/commits/0ea4fe0201e70de4d5622ab43612fe63d9c81c7d

2020-09-22 01:46 UTC, merged