testing go-swagger package
dollarshaveclub/acyl pull request #120
Opened 2020-09-24 01:22 UTC by esterlinej

### Swagger Docs
- Implement generated API documentation (Swagger, etc) and host it somewhere.
- It would make most sense to host in the UI somewhere (access-controlled)

2020-09-28 21:29 UTC, esterlinej commented
<img width="445" alt="Screen Shot 2020-09-28 at 2 28 50 PM" src="https://user-images.githubusercontent.com/231105/94488190-06296e00-0197-11eb-95da-e2d2c9efeb3e.png">
<img width="448" alt="Screen Shot 2020-09-28 at 2 29 05 PM" src="https://user-images.githubusercontent.com/231105/94488198-07f33180-0197-11eb-95f0-5dfca9464cf8.png">
<img width="450" alt="Screen Shot 2020-09-28 at 2 28 58 PM" src="https://user-images.githubusercontent.com/231105/94488203-088bc800-0197-11eb-9e1a-d3e6b243f614.png">

2020-09-28 21:36 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +          description: returns full list of details as defined by the `v0QAEnvironment` struct for each environment
Think it might make sense to reference a swagger definition as opposed to a go struct type? Not sure of the best way to accomplish that though.

2020-09-28 21:38 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +            $ref: '#/definitions/Envs'
When `full_details == true`, this is returned. 

However, when `full_details == false`, it seems just a `[]string` is returned, which contains all the env names. 

Is there a way to encode this information in this swagger file?

2020-09-28 21:52 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +  /envs/:
I'm not exactly sure why there are 2 separate endpoints, `/envs` and `/envs/`, within Acyl. If we are going to document both, then there needs to be some additional detail provided in this document as to why both exists and when to use which one. 

After a quick glance at the code, it seems both of these endpoints do the same thing. In which case, perhaps we just document a single endpoint and mention in the description that a trailing slash is accepted/optional.

2020-09-28 22:06 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +definitions:
Within these definitions, we want to provide definitions of the JSON encoded objects we return to clients. 

HTTP status codes should be removed from this section, unless they are included within the JSON encoded object we return to the client. 

Think this is a reasonable example: 
https://editor.swagger.io/

Sure there are some more examples online too to provide some guidance. We want to provide as much details as possible here as to what is returned to the client.

2020-09-28 22:12 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +tags:
Can we add more details to the descriptions of each of the `v0`, `v1`, and `v2` tags? If possible, it could be helpful to have a general overview of the changes made for `v1` and `v2`.

2020-09-28 22:27 UTC, wwalexander commented on doc/swagger/swagger.yml
> +            $ref: '#/definitions/Envs'
I think this could be done something like

```
oneOf:
  - type: array
     items:
         type: string
  - $ref: '#/definitions/Envs'
    
```

which doesn't encode the condition for each type to be returned, but that can be added as part of the description if necessary.

2020-09-28 22:33 UTC, wwalexander commented on doc/swagger/swagger.yml
> +          description: returns full list of details as defined by the `v0QAEnvironment` struct for each environment
The v0QAEnvironment has a [lot of fields and sub-fields](https://github.com/dollarshaveclub/acyl/blob/0ccbe5555a438d1630f0e906d9516c4c7671416e/pkg/api/api_v0.go#L37). I'm surprised there isn't a common way to automatically generate Swagger type definitions from Go structs...[go-swagger](https://github.com/go-swagger/go-swagger) exists but it has a larger scope.

2020-09-28 22:40 UTC, wwalexander commented
I think that the `pr` query parameter type could be changed to an `integer`, but maybe that's coupling it too tightly with Github choosing to identify PRs by integers. Also I think the `status` query parameter could potentially be an explicit enum:

```yaml
- name: status
  in: query
  description: enviornment status
  required: true
  type: string
  enum:
    - option1
    - option2
```

2020-09-28 22:42 UTC, esterlinej commented on doc/swagger/swagger.yml
> +          description: returns full list of details as defined by the `v0QAEnvironment` struct for each environment
The goal of this isn't to host a server, but utilize this npm package to output yaml -> html, so there may be limitations as to what we can achieve.

2020-09-29 00:05 UTC, esterlinej commented on doc/swagger/swagger.yml
> +            $ref: '#/definitions/Envs'
It appears this package supports 2.0, and that's a 3.0 feature.

2020-09-29 00:06 UTC, esterlinej commented on doc/swagger/swagger.yml
> +          description: returns full list of details as defined by the `v0QAEnvironment` struct for each environment
Added this as a definition, linking to the correct version for each version tag.

2020-09-29 17:33 UTC, esterlinej commented
<img width="456" alt="Screen Shot 2020-09-28 at 6 02 19 PM" src="https://user-images.githubusercontent.com/231105/94595141-42b0a480-023f-11eb-9028-6dd71585cac3.png">
<img width="439" alt="Screen Shot 2020-09-28 at 6 02 36 PM" src="https://user-images.githubusercontent.com/231105/94595145-447a6800-023f-11eb-855e-0bd31118f60a.png">

2020-09-29 18:21 UTC, esterlinej commented
> I think that the `pr` query parameter type could be changed to an `integer`, but maybe that's coupling it too tightly with Github choosing to identify PRs by integers. Also I think the `status` query parameter could potentially be an explicit enum:
> 
> ```yaml
> - name: status
>   in: query
>   description: environment status
>   required: true
>   type: string
>   enum:
>     - UnknownStatus
>     - Spawned
>     - Success
>     - Failure
>     - Destroyed
>     - Updating
> ```

fixed, good catch

2020-09-29 18:23 UTC, mikeykhalil requested changes
Found a few more places where object definitions contained http status codes. I called out a few instances that I saw, but would recommend reviewing to make sure there aren't any additional cases.

2020-09-29 18:23 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +  ClientError:
I don't think Acyl returns a JSON encoded object on most client errors. I believe it just returns an empty body, or a single string (e.g. `not found` or `forbidden`). So I don't think this definition is necessary and all references to it should likely be removed. Otherwise, clients and users might expect the response body to contain this information.

2020-09-29 18:23 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +  ServerError:
I don't think Acyl returns a JSON encoded object on most server errors. I believe it just returns an empty body. So I don't think this definition is necessary and all references to it should likely be removed.

2020-09-29 18:23 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +    properties:
The EventLog doesn't have a `code` property. 

https://github.com/dollarshaveclub/acyl/blob/master/pkg/models/eventlogs.go#L17

2020-09-29 18:23 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +      code:
Don't think and env has a `code` property either

2020-09-29 18:35 UTC, bkeroackdsc requested changes

2020-09-29 18:35 UTC, bkeroackdsc commented on doc/swagger/swagger.yml
> +          required: true
I don't think any of these parameters are strictly required. You just need at least one IIRC.

2020-09-29 18:35 UTC, bkeroackdsc commented on doc/swagger/swagger.yml
> +        - name: API-Key
Is there a way to have a single "Authorization" section that describes API key authentication, instead of duplicating this parameter for every endpoint?

2020-09-29 18:35 UTC, bkeroackdsc commented on doc/swagger/swagger.yml
> +            $ref: '#/definitions/v0QAEnvironment'
Instead of naming these directly after the Go types, I would make them a little more reader-friendly. Something like `QAEnvironment (v0)`.

2020-09-29 18:35 UTC, bkeroackdsc commented on doc/swagger/swagger.yml
> +      responses:
This returns 404 if the environment isn't found I think.

2020-09-29 18:35 UTC, bkeroackdsc commented on doc/swagger/swagger.yml
> +  /envs/{name}/success:
Wow, these still exist! These endpoints (success, failure, event) are holdovers from the original Lambda-based DQA implementation.

I would mark these with big DEPRECATED warnings. I don't think they actually do anything (probably stubbed out).

2020-09-29 18:35 UTC, bkeroackdsc commented on doc/swagger/swagger.yml
> +        - name: full_details
I would mark `full_details` as deprecated. It basically results in a full table dump, which is very inefficient and slow (I believe several seconds of latency).

Clients should use the `_search` endpoint instead.

2020-09-29 18:35 UTC, bkeroackdsc commented on doc/swagger/swagger.yml
> +    description: A representation of AminoServiceToPort object
I would mark all Amino fields as deprecated and unused.

2020-09-29 18:35 UTC, bkeroackdsc commented on doc/swagger/swagger.yml
> +    description: A representation of RefMap object
Explain what a RefMap is (a mapping of repo to git ref <branch>).

2020-09-29 19:14 UTC, esterlinej commented on doc/swagger/swagger.yml
> +  /envs/{name}/success:
Okay, I will comment that in the API files themselves as well as in the swagger docs

2020-09-29 20:11 UTC, esterlinej commented
<img width="450" alt="Screen Shot 2020-09-29 at 1 10 10 PM" src="https://user-images.githubusercontent.com/231105/94610531-48b18000-0255-11eb-8dce-04d05146d4a8.png">
<img width="455" alt="Screen Shot 2020-09-29 at 1 10 04 PM" src="https://user-images.githubusercontent.com/231105/94610537-4a7b4380-0255-11eb-99fc-f8ad60c43dd6.png">

2020-09-29 20:45 UTC, mikeykhalil requested changes

2020-09-29 20:45 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +  EventLog:
Still think there is room to list the properties of an `EventLog` here. I'm not sure if we necessarily need to go into full detail here (since there is a lot of data that is more easily found in other endpoints), but at least mentioning the response contains a `log` property of type `[]string` would be helpful for users so they can parse the response accordingly.

2020-09-29 20:52 UTC, esterlinej commented on doc/swagger/swagger.yml
> +  EventLog:
Sure, will update.

2020-09-29 22:57 UTC, mikeykhalil requested changes
Looks good to me!

2020-09-29 22:57 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +          description: returns list of detailed environments as defined by `QAEnvironment (v2)`
The description says `returns list of detailed environments as defined by `QAEnvironment (v2)`,
but the schema for the same response code is `'#/definitions/Envs'`

Should the schema instead be an array of `'#/definitions/QAEnvironment_v2'? Or does the description need to be updated?

2020-09-29 22:57 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +          description: returns list of detailed environments as defined by `QAEnvironment (v0)`
The description says returns list of detailed environments as defined by QAEnvironment (v0), but the schema for the same response code is `'#/definitions/Envs'`

Should the schema instead be an array of `'#/definitions/QAEnvironment_v0'`? Or does the description need to be updated?

2020-09-29 22:57 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +            $ref: '#/definitions/Envs'
The description says returns list of detailed environments as defined by QAEnvironment (v9), but the schema for the same response code is '#/definitions/Envs'`

Should the schema instead be an array of `'#/definitions/QAEnvironment_v0'? Or does the description need to be updated?

2020-09-29 22:57 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +            $ref: '#/definitions/Envs'
The description says returns list of detailed environments as defined by QAEnvironment (v1), but the schema for the same response code is '#/definitions/Envs'`

Should the schema instead be an array of `'#/definitions/QAEnvironment_v1'? Or does the description need to be updated?

2020-09-29 22:57 UTC, mikeykhalil commented on doc/swagger/swagger.yml
> +            $ref: '#/definitions/Envs'
The description says returns list of detailed environments as defined by QAEnvironment (v1), but the schema for the same response code is '#/definitions/Envs'`

Should the schema instead be an array of `'#/definitions/QAEnvironment_v1'? Or does the description need to be updated?

2020-09-29 22:58 UTC, esterlinej commented on doc/swagger/swagger.yml
> +            $ref: '#/definitions/Envs'
We could update this, the Envs represent an array of these objects, it was meant to be more generic to cover all of the same types

2020-09-29 23:21 UTC, esterlinej commented
<img width="896" alt="Screen Shot 2020-09-29 at 4 19 06 PM" src="https://user-images.githubusercontent.com/231105/94626387-ddc17280-026f-11eb-9225-0370fcaf5f1e.png">
<img width="436" alt="Screen Shot 2020-09-29 at 4 15 43 PM" src="https://user-images.githubusercontent.com/231105/94626393-def29f80-026f-11eb-9747-aae5380ce8c1.png">

2020-09-29 23:24 UTC, mikeykhalil approved these changes

2020-09-29 23:25 UTC, bkeroackdsc approved these changes

2020-09-29 23:28 UTC, merged