Add Help View
dollarshaveclub/acyl pull request #122
Opened 2020-10-01 02:38 UTC by esterlinej

### Help View
- Implement a “Help” view which contains links to documentation and utilities that are helpful for developing/testing environment configs.
- Use one of these icons in the main navigation bar for the Help view (from Font Awesome):
- Link to Swagger API documentation
### Added Feature
- Support custom urls, `Added Resources` urls

2020-10-01 02:38 UTC, esterlinej commented
<img width="372" alt="Screen Shot 2020-09-30 at 7 27 40 PM" src="https://user-images.githubusercontent.com/231105/94759350-86490280-0354-11eb-8414-57eee2d4cf20.png">
<img width="327" alt="Screen Shot 2020-09-30 at 7 27 08 PM" src="https://user-images.githubusercontent.com/231105/94759355-8812c600-0354-11eb-8fba-7e5750f4532a.png">

2020-10-01 21:50 UTC, mikeykhalil commented on cmd/mockui.go
> +	cmd.PersistentFlags().StringSliceVar(&serverConfig.UIExternalDocumentURLs, "ui-doc-urls", []string{}, "External documentation URLs")
Do we need a value for this in the helm chart?

2020-10-01 21:54 UTC, esterlinej commented on cmd/mockui.go
> +	cmd.PersistentFlags().StringSliceVar(&serverConfig.UIExternalDocumentURLs, "ui-doc-urls", []string{}, "External documentation URLs")
We can, it's not required at this time, but will update the helm chart after this before we deploy this release to add our confluence docs

2020-10-01 21:56 UTC, esterlinej commented on cmd/mockui.go
> +	cmd.PersistentFlags().StringSliceVar(&serverConfig.UIExternalDocumentURLs, "ui-doc-urls", []string{}, "External documentation URLs")
2nd thought, you're right, will add.

2020-10-01 22:05 UTC, mikeykhalil commented on ui/assets/help.js
> +    arh.removeAttribute("class");
how come we are removing the class entirely here?

2020-10-01 22:07 UTC, mikeykhalil commented on ui/assets/help.js
> +    let arh = document.getElementById("hAdditionalResources");
Perhaps we should do a null check here as well?
```
if (arh == null) {
        return;
    }
```

2020-10-01 22:12 UTC, mikeykhalil commented on ui/assets/help.js
> +            console.log(`namespace pods request failed: ${req.status}: ${req.responseText}`);
```suggestion
 console.log(`help document request failed: ${req.status}: ${req.responseTest}`);
```

2020-10-01 22:15 UTC, mikeykhalil commented on ui/assets/help.js
> +        console.error(`error getting namespace pod endpoint for ${env_name}: ${req.statusText}`);
```suggestion
console.error(`error getting help documents: ${req.statusText}`);
```

2020-10-01 22:19 UTC, mikeykhalil commented on pkg/api/api_v2.go
> +func (api *v2api) externalDocumentURLsHandler(w http.ResponseWriter, r *http.Request) {
Since these values don't change during the lifetime of the server, could we just render the urls when we go to serve the html/javascript assets? Or are there other benefits for making an endpoints for this?

2020-10-01 22:28 UTC, esterlinej commented on ui/assets/help.js
> +    arh.removeAttribute("class");
The class by default bootstap is hidden, so to show it, we need to remove the class

2020-10-01 22:28 UTC, esterlinej commented on pkg/api/api_v2.go
> +func (api *v2api) externalDocumentURLsHandler(w http.ResponseWriter, r *http.Request) {
Slack Huddle...

2020-10-01 23:49 UTC, esterlinej commented on pkg/api/api_v2.go
> +func (api *v2api) externalDocumentURLsHandler(w http.ResponseWriter, r *http.Request) {
Updated, thanks for the brain storm, resolving

2020-10-02 00:14 UTC, bkeroackdsc requested changes

2020-10-02 00:14 UTC, bkeroackdsc commented on pkg/api/api_ui.go
> +func newUIAPI(baseURL, assetsPath, routePrefix string, reload bool, branding config.UIBrandingConfig, dl persistence.DataLayer, oauthCfg OAuthConfig, logger *log.Logger, docUrls []string) (*uiapi, er
`docURLs` can probably be put into UIBrandingConfig.

2020-10-02 00:14 UTC, bkeroackdsc commented on pkg/config/config.go
> +	UIExternalDocumentURLs     []string
This should be a map of name to URL, which then gets templated like this: 
`<a href="{{ url }}">{{ name }}</a>`

2020-10-02 00:14 UTC, bkeroackdsc commented on ui/views/help.html
> +                src="{{ .APIBaseURL }}/ui/static/help.js"
There is no help.js so you can get rid of this.

2020-10-02 00:14 UTC, bkeroackdsc commented on cmd/mockui.go
> +	cmd.PersistentFlags().StringSliceVar(&serverConfig.UIExternalDocumentURLs, "ui-doc-urls", []string{}, "External documentation URLs")
Since we need both link name and URL (not just URL as you have here), I would either do this as a string slice of `<name>=<url>` strings, or as a single JSON-encoded array of objects: `[{"name": "foo", "url": "bar"}]`.

You could even extend the JSON branding configuration (the option above) to include additional documentation URLs.

2020-10-02 20:22 UTC, bkeroackdsc requested changes

2020-10-02 20:22 UTC, bkeroackdsc commented on .helm/charts/acyl/values.yaml
> +    document_urls: ''
Incorrect indentation

2020-10-02 20:22 UTC, bkeroackdsc commented on cmd/mockui.go
> +	log.Println(serverConfig.UIBrandingJSON)
Remove debug printlns

2020-10-02 20:22 UTC, bkeroackdsc commented on pkg/config/config.go
> +	AdditionalDocUrls map[string]string `json:"additional_doc_urls"`
Naming: `AdditionalDocURLs`

2020-10-02 20:25 UTC, bkeroackdsc approved these changes

2020-10-02 20:31 UTC, merged