Acyl Feature: API Keys
dollarshaveclub/acyl pull request #128
Opened 2020-10-06 01:13 UTC by esterlinej

### API Keys
Currently Acyl has a list of API keys (UUIDs) that are read from Vault at startup and then checked via the auth request middleware in pkgs/api/middleware.go.

In preparation for user-managed API keys, we need to create a new table in the database (api_keys) with the following columns (_add anything that's missing from this list as needed_):
- API key (random UUID), this should be the primary key
- created & last used timestamps
- permissions level (probably an integer-based enum: read-only, read-write, or admin)
- name string
- description string
- github user string

Models and Datalayer methods + tests will need to be implemented for basic CRUD operations: Create, Get, Delete, Update last used timestamp only (everything else should be immutable).

**We should continue to support the legacy list of static API keys from Vault**, but in addition to this, every time an API call is made we should also check the API key supplied by the client against the keys in the database, and authorize the API call if a database API key matches and has sufficient permissions.

For now, all endpoints except `DELETE /envs/<name>` should be considered read-only and require read-only key permissions. The delete environment endpoint should be considered read-write. There are no admin-only endpoints currently. Static API keys from Vault should be treated as admin keys.

2020-10-09 18:51 UTC, bkeroackdsc requested changes
You're missing the functionality from the second half of the ticket. Specifically, authorizing API calls against keys that exist in the database (utilizing the datalayer methods you've implemented).

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/models/apikeys.go
> +type PermissionsLevels int
Name should be `PermissionLevel` (singular).

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/models/apikeys.go
> +)
Enums should usually start with an unknown value so that the zero value can be distinguished.

The names should also include the type because these are package-level types and thus "ReadOnly" is not descriptive enough within the entire `models` package.

```go
const (
   UnknownPermission PermissionLevel = iota
   ReadOnlyPermission
   WritePermission
   AdminPermission
)
```

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/models/apikeys.go
> +func (apik APIKey) DecodePermissionsLevel(pl PermissionsLevels) string {
Use `go generate` with stringer here to autogenerate strings from enums.

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/persistence/apikeys.go
> +		APIKey: uuid.New(),
This should be `uuid.NewRandom()` with the error checked.

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/persistence/apikeys.go
> +		LastUsed: pq.NullTime{Time: time.Now().UTC().Truncate(1 * time.Microsecond), Valid: true},
I don't think you need to truncate times here.

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/persistence/apikeys.go
> +	in.PermissionsLevel = in.EncodePermissionsLevel(permissionsLevel)
You're converting to string but the column type is integer.

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/persistence/apikeys.go
> +	if err := pg.db.QueryRowContext(ctx, q, in.InsertValues()...).Scan(&id); err != nil {
This can be an `Exec()` since you already have the id so the "RETURNING ..." clause is unnecessary.

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/persistence/apikeys.go
> +	_, err := pg.db.ExecContext(ctx, q, pq.NullTime{Time: time.Now().UTC().Truncate(1 * time.Microsecond), Valid: true}, id)
You don't need to truncate time.

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/persistence/fake.go
> +	apikeys    map[string][]*models.APIKey
The map key should be `uuid.UUID`.

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/persistence/fake.go
> +		APIKey: uuid.New(),
`uuid.NewRandom()`

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/persistence/fake.go
> +		Created: time.Now().UTC().Truncate(1 * time.Microsecond),
Don't truncate time.

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/persistence/fake.go
> +}
You have this backward. Map key should be UUID, and to find keys by user you should iterate through the data set.

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/persistence/fake.go
> +				v.LastUsed = pq.NullTime{Time: time.Now().UTC().Truncate(1 * time.Millisecond), Valid: true}
Truncating time again.

2020-10-09 18:51 UTC, bkeroackdsc commented on pkg/persistence/fake.go
> +				fdl.data.apikeys[v.GitHubUser] = append(fdl.data.apikeys[v.GitHubUser][:k], fdl.data.apikeys[v.GitHubUser][k+1:]...)
This would just be a simple map key delete if the key was a UUID and not a github user.

2020-10-14 23:06 UTC, esterlinej commented on pkg/persistence/apikeys.go
> +	in.PermissionsLevel = in.EncodePermissionsLevel(permissionsLevel)
This encode pl takes the string and converts it into an integer

2020-10-15 01:13 UTC, bkeroackdsc requested changes

2020-10-15 01:13 UTC, bkeroackdsc commented on pkg/api/api_v0.go
> +	r.HandleFunc("/envs/{name}", middlewareChain(authMiddleware.tokenAuth(api.envDestroyHandler, models.WritePermission), waitMiddleware.waitOnRequest)).Methods("DELETE")
On second thought, this should require Admin permissions since otherwise it would allow any user to delete any environment (not just their own).

2020-10-15 01:13 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +			apikey, err := authMiddleware.DL.GetAPIKeyById(r.Context(), uuid.MustParse(key))
`uuid.MustParse()` will panic if the UUID can't be parsed (which would kill the whole process). Instead, parse and check the error.

2020-10-15 01:13 UTC, bkeroackdsc commented on pkg/persistence/apikeys.go
> +		Created:     time.Now().UTC().Truncate(1 * time.Microsecond),
You don't need to truncate time.

2020-10-15 01:13 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +				f(w, r)
Update the last used timestamp here.

2020-10-15 01:13 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +				w.WriteHeader(http.StatusInternalServerError)
Log the error.

2020-10-15 01:13 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +				w.WriteHeader(http.StatusNotFound)
`StatusForbidden` not a 404.

2020-10-15 01:13 UTC, bkeroackdsc commented on pkg/persistence/datalayer.go
> +	CreateAPIKey(ctx context.Context, permissionLevel, name, description, githubUser string) (uuid.UUID, error)
`permissionLevel` should be `models.PermissionLevel` instead of string.

2020-10-15 01:13 UTC, bkeroackdsc commented on pkg/persistence/fake.go
> +	for _, v := range fdl.data.apikeys {
Do a map lookup instead of iterating through it.

2020-10-15 01:13 UTC, bkeroackdsc commented on pkg/persistence/fake.go
> +	for _, v := range fdl.data.apikeys {
Map lookup not iteration.

2020-10-15 01:13 UTC, bkeroackdsc commented on pkg/persistence/fake.go
> +	for _, v := range fdl.data.apikeys {
Map lookup not iteration

2020-10-15 01:24 UTC, esterlinej commented on pkg/persistence/apikeys.go
> +		Created:     time.Now().UTC().Truncate(1 * time.Microsecond),
Missed this one, will remove

2020-10-15 16:31 UTC, esterlinej commented on pkg/api/middleware.go
> +			if apikey != nil {
Rather than return `Forbidden` on nil, I flipped this logic `if not nil` then check and update, otherwise it kicks down to `Unauthorized`, which was the default experience with `authRequest`

2020-10-15 16:47 UTC, bkeroackdsc requested changes

2020-10-15 16:47 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +				return
Bad/invalid API key should be a StatusForbidden error, not a 500.

2020-10-15 16:47 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +				w.WriteHeader(http.StatusInternalServerError)
Error parsing the key (meaning bad/invalid key) should be a StatusForbidden, not a 500.

2020-10-15 16:47 UTC, bkeroackdsc commented on pkg/models/apikeys.go
> +}
You don't need this encoding/decoding. Just use the enum values.

2020-10-15 16:47 UTC, bkeroackdsc commented on pkg/persistence/fake.go
> +	fdl.data.Lock()
Since this is a read-only method, this should be `fdl.data.RLock()` and `RUnlock()`

2020-10-15 16:47 UTC, bkeroackdsc commented on pkg/persistence/fake.go
> +	fdl.data.Lock()
`RLock()` and `RUnlock()`

2020-10-15 17:30 UTC, bkeroackdsc approved these changes

2020-10-15 17:32 UTC, merged