Add cancelled status when preemption is detected
dollarshaveclub/acyl pull request #133
Opened 2020-10-09 22:16 UTC by wwalexander

This commit additionally moves from github.com/pkg/errors to Go 1.13's native error-wrapping in pkg/nitro/env.

2020-10-10 00:06 UTC, mikeykhalil commented on pkg/nitro/env/env.go
> +		cancelled = true
I wonder if we could just do `nitroerrors.CancelledError(ctx.Err())` here, as opposed to keeping track of this boolean.

Then, once we verify that `err != nil` below, we can do something like 

```
if nitroerrors.IsCanceledError(err) { 
  eventlogger.GetLogger(ctx).SetCompletedStatus(models.CancelledStatus)
} else { 
  eventlogger.GetLogger(ctx).SetFailedStatus(ce)
}
```

2020-10-10 00:12 UTC, mikeykhalil commented on pkg/models/eventlogs.go
> +	CancelledStatus
A comment earlier on in this file indicates that there is code that needs to be regenerated after this change
```
//go:generate stringer -type=EventStatus
```

2020-10-10 00:34 UTC, wwalexander commented on pkg/models/eventlogs.go
> +	CancelledStatus
Should be fixed by 9fe8e4c.

2020-10-10 00:35 UTC, wwalexander commented on pkg/nitro/env/env.go
> +		cancelled = true
That makes more sense! Should be fixed by 9fe8e4c.

2020-10-14 00:40 UTC, bkeroackdsc requested changes

2020-10-14 00:40 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +	if nitroerrors.IsCancelledError(err) {
You're wrapping the error, but then checking just a few lines down. Something like this would be simpler: https://gist.github.com/bkeroackdsc/f58b017235861eaa23461528939d89c8

2020-10-14 00:40 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +	} else {
I would do an early return here instead of the `else` clause.

2020-10-14 00:40 UTC, bkeroackdsc commented on ui/assets/env.js
> +            break;
We're not changing the Environment Status, just the event status.

2020-10-14 00:45 UTC, wwalexander commented on ui/assets/env.js
> +            break;
I think I'm missing something - this switch is on event.status so the cancelled status should have it's own representation, no?

2020-10-14 01:04 UTC, wwalexander commented on pkg/nitro/env/env.go
> +	} else {
Should be fixed by f668249.

2020-10-14 01:04 UTC, wwalexander commented on pkg/nitro/env/env.go
> +	if nitroerrors.IsCancelledError(err) {
Should be fixed by f668249.

2020-10-14 01:09 UTC, bkeroackdsc commented on ui/assets/env.js
> +            break;
You're correct, my mistake.

2020-10-14 01:31 UTC, bkeroackdsc approved these changes
LGTM

2020-10-14 21:45 UTC, merged