Use explicit errors to detect system/user/cancellation errors
dollarshaveclub/acyl pull request #135
Opened 2020-10-21 03:16 UTC by wwalexander

2020-10-22 19:59 UTC, mikeykhalil requested changes
LGTM, just notice that a lot of the `if err != nil { ` blocks contain an extra trailing `\n`. So those should probably be removed to keep things consistent. 

I do remember @bkeroackdsc had some opinions and thoughts around classifying system errors versus user errors, so I would ensure to make sure he reviews before merging.

2020-10-23 18:12 UTC, bkeroackdsc requested changes
My main issue is that you don't need to explicitly annotate errors as System Errors. Any error is implicitly a system error if it is not annotated explicitly as a User Error.

Also, I think we should take this opportunity to update to Go 1.15 and make sure all our images are using consistent versions (Dockerfile, CircleCI).

https://github.com/dollarshaveclub/acyl/blob/71d3feffc75c78738eedd3b3bd9f8d576c10904f/.circleci/config.yml#L6
https://github.com/dollarshaveclub/acyl/blob/71d3feffc75c78738eedd3b3bd9f8d576c10904f/.circleci/config.yml#L16
https://github.com/dollarshaveclub/acyl/blob/71d3feffc75c78738eedd3b3bd9f8d576c10904f/Dockerfile#L1

2020-10-23 18:12 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +		return "", fmt.Errorf("error installing charts: %w", nitroerrors.UserError(err))
This is another instance where you can't reliably tell at this point in the callstack whether this is a user or system error (might be a misconfigured helm chart, or the K8s control plane could be having problems, etc).

2020-10-23 18:12 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +				return fmt.Errorf("error getting environments associated with the repo (%v) and PR (%v): %w", rd.Repo, rd.PullRequest, nitroerrors.SystemError(err))
System error wrapping should rarely (if ever) be used. *Everything* is a system error, unless it's specifically annotated as a User Error.

2020-10-23 18:12 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +		return fmt.Errorf("error getting extant environment: %w", nitroerrors.SystemError(err))
Same here. Eliminate all these SystemError() annotations. Perhaps just remove that annotation function entirely.

2020-10-23 18:12 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +			return envinfo.Env.Name, fmt.Errorf("error upgrading charts: %w", nitroerrors.UserError(err))
You can't tell whether this is a User Error or not.

My approach would be to do this annotation in `pkg/nitro/metahelm`. If a FailedEnvironment report is returned, then it is a User Error (probably misconfigured chart), otherwise it's a system error.

2020-10-23 18:12 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +		return "", fmt.Errorf("error installing charts: %w", nitroerrors.UserError(err))
Same.

2020-10-23 18:12 UTC, bkeroackdsc commented on pkg/nitro/errors/errors.go
> +}
There's no need to enumerate system errors.

2020-10-23 18:12 UTC, bkeroackdsc commented on pkg/nitro/errors/errors.go
> +}
There's no need for this enumeration because any named error constant is by definition a User Error.

2020-10-23 18:12 UTC, bkeroackdsc commented on pkg/nitro/errors/errors.go
> +	}
It would be more efficient to have a named error type and then check for type equality.
```go
uerr, ok := err.(*UserError)
return ok
```

2020-10-23 18:12 UTC, bkeroackdsc commented on pkg/nitro/meta/meta.go
> +)
Nice 👍

2020-10-23 18:12 UTC, bkeroackdsc commented on pkg/nitro/meta/meta.go
> +var (
Unnecessary.

2020-10-23 18:12 UTC, bkeroackdsc commented on pkg/nitro/meta/meta.go
> +		return ErrYAMLSyntax
You need to wrap the original error so that information about the syntax error isn't lost.

2020-10-24 00:57 UTC, wwalexander commented on pkg/nitro/env/env.go
> +		return "", fmt.Errorf("error installing charts: %w", nitroerrors.UserError(err))
I think that we might not be able to reliably differentiate those types of errors here, as m.CI is an interface, so we'd have to add requirements to the metahelm.Installer interface to return specific error types. Should we just leave this as a system error?

2020-10-27 23:24 UTC, closed without merging