Add and set environment cancellation status
dollarshaveclub/acyl pull request #138
Opened 2020-10-29 01:54 UTC by wwalexander

This PR adds a Cancelled environment status. This status is set when an operation on the environment (Create, Update, or Delete) is cancelled via a context.

2020-10-29 18:54 UTC, bkeroackdsc requested changes

2020-10-29 18:54 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +	if cancelled {
`if nitroerrors.IsCancelledError(err) {`

2020-10-29 18:54 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +	return name, nil
`return name, err`

2020-10-29 18:54 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +	if cancelled {
`if nitroerrors.IsCancelledError(err) {`

2020-10-29 18:54 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +func (m *Manager) setStatus(ctx context.Context, rd models.RepoRevisionData, status models.EnvironmentStatus) error {
This method doesn't seem necessary. I think you can just use `m.DL.SetQAEnvironmentStatus()` in the places where you use this method.

2020-10-29 18:54 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +	if cancelled {
See previous comment.

2020-10-29 18:54 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +	return name, nil
See previous comment.

2020-10-29 19:52 UTC, wwalexander commented on pkg/nitro/env/env.go
> +	if cancelled {
Whoops, had this in from an earlier version where I used the value again and didn't want to unwrap the error stack twice. Fixed by b52daf6.

2020-10-29 19:52 UTC, wwalexander commented on pkg/nitro/env/env.go
> +	return name, nil
Fixed by b52daf6.

2020-10-29 19:53 UTC, wwalexander commented on pkg/nitro/env/env.go
> +func (m *Manager) setStatus(ctx context.Context, rd models.RepoRevisionData, status models.EnvironmentStatus) error {
Fixed by b52daf6.

2020-10-29 19:53 UTC, wwalexander commented on pkg/nitro/env/env.go
> +	return name, nil
Fixed by b52daf6.

2020-10-29 19:53 UTC, wwalexander commented on pkg/nitro/env/env.go
> +	if cancelled {
Fixed by b52daf6.

2020-11-02 21:33 UTC, bkeroackdsc requested changes

2020-11-02 21:33 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +		}
I think we can safely disregard any error from `m.getenv()` in this code, because there may be instances where an event gets cancelled but there is no extant environment yet (maybe this was the first create event, and it was cancelled before an environment was ever persisted in the database).

Keep in mind also that `ctx` here is guaranteed to be cancelled, so for `getenv()` you'll need to use a new context otherwise the datalayer methods will return errors.

Change to something like:
```go
env, err2 := m.getenv(ctx, &rd)
if err2 == nil {
   // set cancelled status
}
return name, err
```

2020-11-02 21:33 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +			err = fmt.Errorf("error persisting cancelled status after cancellation: %w", err)
You should log this (using the event logger) but don't clobber the original error.

2020-11-02 21:33 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +		env, err := m.getenv(ctx, &rd)
See comments above. The same applies here.

2020-11-02 22:31 UTC, wwalexander commented on pkg/nitro/env/env.go
> +		env, err := m.getenv(ctx, &rd)
Should be fixed by c2746e2.

2020-11-02 22:31 UTC, wwalexander commented on pkg/nitro/env/env.go
> +		}
Should be fixed by c2746e2.

2020-11-02 22:31 UTC, wwalexander commented on pkg/nitro/env/env.go
> +			err = fmt.Errorf("error persisting cancelled status after cancellation: %w", err)
Should be fixed by c2746e2.

2020-11-02 23:34 UTC, bkeroackdsc requested changes

2020-11-02 23:34 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +		ctx := context.Background()
Don't shadow/overwrite `ctx` because the existing context contains the eventlogger that you need below. Just do `env, envErr := m.getenv(context.Background(), &rd)`

2020-11-02 23:34 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +			m.log(ctx, "error persisting cancelled status after cancellation: %v", err)
This wouldn't work (would get logged to a null eventlogger) because you've shadowed `ctx` above.

2020-11-03 00:22 UTC, wwalexander commented on pkg/nitro/env/env.go
> +			m.log(ctx, "error persisting cancelled status after cancellation: %v", err)
Fixed by 4a69411.

2020-11-03 00:22 UTC, wwalexander commented on pkg/nitro/env/env.go
> +		ctx := context.Background()
Fixed by 4a69411.

2020-11-03 00:26 UTC, bkeroackdsc requested changes

2020-11-03 00:26 UTC, bkeroackdsc commented on pkg/nitro/env/env.go
> +		if err := m.DL.SetQAEnvironmentStatus(ctx, env.Name, models.Cancelled); err != nil {
You'll need to use `context.Background()` here as well (because ctx is cancelled).

2020-11-03 00:55 UTC, wwalexander commented on pkg/nitro/env/env.go
> +		if err := m.DL.SetQAEnvironmentStatus(ctx, env.Name, models.Cancelled); err != nil {
Whoops, sorry for missing that! Fixed by 5b5acc3.

2020-11-03 01:22 UTC, bkeroackdsc approved these changes

2020-11-04 22:50 UTC, merged