Don't report CancelledErrors as errors to Datadog
dollarshaveclub/acyl pull request #143
Opened 2020-11-18 00:19 UTC by wwalexander

This PR avoids reporting CancelledErrors as errors via span.Finish to the webhook_processor span. I think this could also be implemented as adding a tag like `is_cancelled` and then filtering the metric based on the value of that tag, if we want to preserve info on when cancellations have occurred.

2020-11-18 17:24 UTC, bkeroackdsc requested changes

2020-11-18 17:24 UTC, bkeroackdsc commented on pkg/api/api_v0.go
> +		span.Finish(tracer.WithError(err))
Offhand I think `tracer.WithError(nil)` is the same as `span.Finish()` so this can be simplified.

2020-12-17 18:33 UTC, bkeroackdsc approved these changes

2020-12-17 22:16 UTC, esterlinej reviewed
lgtm

2020-12-18 00:26 UTC, merged