Acyl Feature: Refactor UI API Docs
dollarshaveclub/acyl pull request #150
Opened 2020-12-15 03:02 UTC by esterlinej

- replace bootprint with base openapi-generator
- generated docs (failing)
- (wip) rebuilding swagger yaml
- update swagger script

2020-12-17 01:13 UTC, esterlinej commented
<img width="609" alt="Screen Shot 2020-12-16 at 7 12 35 PM" src="https://user-images.githubusercontent.com/231105/102425359-c96d5600-3fd2-11eb-8b5a-c0a2942d320f.png">
<img width="630" alt="Screen Shot 2020-12-16 at 7 13 14 PM" src="https://user-images.githubusercontent.com/231105/102425377-cffbcd80-3fd2-11eb-864f-88e82fb67fa3.png">

2020-12-17 17:58 UTC, bkeroackdsc requested changes
- You probably should add explicit API key permissions to each endpoint (IIRC, only the DELETE env endpoint requires admin key permissions).
- `/apidocs` is better than `/doc`

2020-12-17 22:17 UTC, esterlinej commented
Update to output html2, provides updated view
<img width="870" alt="Screen Shot 2020-12-17 at 4 14 44 PM" src="https://user-images.githubusercontent.com/231105/102550221-14df3d00-4083-11eb-80f9-90e2734862d0.png">
<img width="875" alt="Screen Shot 2020-12-17 at 4 14 55 PM" src="https://user-images.githubusercontent.com/231105/102550225-1577d380-4083-11eb-8a47-0061a708b15d.png">

2020-12-17 22:49 UTC, bkeroackdsc requested changes

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +            admin: requires admin api key privileges
Omit. This shouldn't be used by API consumers. In the future, UI json API endpoints may also support API key auth.

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +      description: API Key with required github_auth permission level or aborts with Unauthorized
This isn't "github_auth" permission level, it's the permission level of the api key when it was created.

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +      description: A representation of QAEnvironmentEvent object
This description is tautological ("X is a representation of X").

Give a useful description: "This is data representing an event associated with an environment object"

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +      description: A representation of RefMap object; map of repo to git reference
"Map of repo name to git reference (branch)."

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +      description: A representation of a v0 environment
What is a "v0 environment"? Be more descriptive.

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +        raw_events:
I'm not sure if this actually is part of the JSON payload. Double check.

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +          type: string
I'm pretty sure these are deprecated & unused.

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +          type: string
Call out that these are fields of the triggering Pull Request. Explain what a "base SHA/branch" and "source SHA/branch" are (and why they are different).

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +        raw_status:
I don't believe this is part of the JSON response.

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +          type: integer
Explain that this is an integer-based enum and give the possible values (X: success, Y: failed, etc).

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +          type: integer
Deprecated, unused. API clients should ignore.

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +      description: A representation of a v1 environment
Summarize the differences between a v0 environment response and a v1 response. See the API changelog for details.

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +          $ref: '#/components/schemas/RefMap'
Commit SHA map is different from a ref map. Refmap uses branch names, commit sha map uses full commit shas.

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +      description: A representation of a v2 environment
Summarizes changes from v1.

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +      description: A representation of an event log response
Describe more fully what this is, and what an event log contains. Why is it useful?

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +          type: string
UUID.

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +          type: string
Explain that this is a time-ordered array of debug log messages associated with this specific event.

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +        type: string
integer

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +        type: string
UUID

2020-12-17 22:49 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +        type: string
integer (IIRC)

2020-12-18 00:34 UTC, esterlinej commented on doc/generate/openapi.yml
> +          type: string
They still exist in the response struct, but I can add `deprecated: true` to this field

2020-12-18 01:47 UTC, esterlinej commented on doc/generate/openapi.yml
> +          type: integer
<img width="940" alt="Screen Shot 2020-12-17 at 7 47 29 PM" src="https://user-images.githubusercontent.com/231105/102564304-bde86080-40a0-11eb-99b6-2ca7201819ca.png">

2020-12-18 02:49 UTC, esterlinej commented
Updated most descriptions
<img width="747" alt="Screen Shot 2020-12-17 at 8 48 54 PM" src="https://user-images.githubusercontent.com/231105/102568538-4d920d00-40a9-11eb-9fe4-4e61b3b1b0e9.png">

2020-12-18 17:18 UTC, esterlinej commented
Made one final push updating summary and description text, also adding missing update to status in the screen cap above.

2020-12-18 17:18 UTC, esterlinej commented
![Uploading Screen Shot 2020-12-17 at 7.47.29 PM.png…]()

2020-12-18 17:18 UTC, esterlinej commented
<img width="940" alt="Screen Shot 2020-12-17 at 7 47 29 PM" src="https://user-images.githubusercontent.com/231105/102642107-c84b3e80-4122-11eb-94d3-f05c1335c87a.png">

2020-12-18 17:58 UTC, bkeroackdsc requested changes

2020-12-18 17:58 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +          description: "GitHub SHA for the master branch"
"GitHub HEAD commit SHA for the branch the PR will merge into (eg, master)."

2020-12-18 17:58 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +          description: "GitHub name of the master branch"
"GitHub branch name the PR will merge into (eg, master)."

2020-12-18 17:58 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +      description: "This data represents a map of repo name to git reference (branch) object response"
Remove the word "data" and the phrase "object response" from each of these descriptions.

2020-12-18 17:58 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +          description: "GitHub username of the requesting user"
"GitHub username of the user who opened the triggering PR."

2020-12-18 17:58 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +      summary: "Search environments from optional parameters, at least one parameter is required"
Point out that multiple parameters are combined with a logical AND. PR = X *and* repo = Y *and* status = Z, etc.

2020-12-18 17:58 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +  /envs/{name}/success:
I second thought, I think you can get rid of all these old endpoints. They almost certainly don't do anything and nobody should be trying to use them. They're just clutter at this point.

2020-12-18 18:00 UTC, bkeroackdsc commented on doc/generate/openapi.yml
> +  /envs/{name}/success:
I mean, remove them from the API docs. Later on we can remove them from the codebase as well.

2020-12-18 19:32 UTC, bkeroackdsc approved these changes

2020-12-18 20:09 UTC, merged