Implement User API Keys
dollarshaveclub/acyl pull request #153
Opened 2021-01-13 23:42 UTC by esterlinej

## Requirements
- In the user settings view, implement the ability to create and delete API tokens
- Users should be able to name them with an optional description
- Users should see a list of their currently-active API tokens (names/descriptions) with the ability to delete them as needed.

---
### Changes
- Middleware inserts bool, user key model into context for use with handlers
- Add user authorization checks for specific endpoints
- Checks first for admin, then user key to authorize

2021-01-19 22:49 UTC, wwalexander commented on pkg/api/api_v0.go
> +	if !r.Context().Value(acylAPIKey).(bool) {
I think this could potentially be simplified to:

```
key, ok := r.Context().Value(userAPIKey).(models.APIKey)
if !ok || key.GitHubUser != qa.User {
    api.forbiddenError(w, "request not authorized")
    return
}
```

2021-01-19 23:25 UTC, wwalexander commented on pkg/api/api_v2.go
> +		w.WriteHeader(http.StatusInternalServerError)
Writing a header after starting the body isn't supported by HTTP AFAIK; you could buffer the JSON if you need to be able to detect encoding failures or use [trailers](https://golang.org/pkg/net/http/#example_ResponseWriter_trailers)

2021-01-19 23:55 UTC, esterlinej commented on pkg/api/api_v0.go
> +	if !r.Context().Value(acylAPIKey).(bool) {
I will look into this, the issue is we need to let Admin (acyl api key) go through if true, otherwise we check for user api key.

2021-01-19 23:56 UTC, esterlinej commented on pkg/api/api_v2.go
> +		w.WriteHeader(http.StatusInternalServerError)
So review all other handlers, this is done the exact same way.

2021-01-20 00:23 UTC, wwalexander approved these changes
LGTM besides for the couple of random nitpicks I had.

2021-01-20 00:27 UTC, wwalexander commented on pkg/api/api_v0.go
> +	if !r.Context().Value(acylAPIKey).(bool) {
Ah yeah, I left that comment in a misleading spot, I was thinking it would go inside the check for the acylAPIKey, e.g.

```
if !r.context().Value(acylAPIKey).(bool) {
    key, ok := r.Context().Value(userAPIKey).(models.APIKey)
    if !ok || key.GitHubUser != qa.User {
        api.forbiddenError(w, "request not authorized")
        return
    }
}
```

2021-01-20 00:31 UTC, esterlinej commented on pkg/api/api_v0.go
> +	if !r.Context().Value(acylAPIKey).(bool) {
So given that we need to first check for acyl api key, and continue if found, we'd need to wrap it to account for both options, cause if false and no user key exists or doesnt match, it needs to error for this as well. Using your suggestion, I have rewritten as such:
```
if !r.Context().Value(acylAPIKey).(bool) {
	var authorized bool
	key, ok := r.Context().Value(userAPIKey).(models.APIKey)
	if ok && key.GitHubUser == qa.User {
		authorized = true
	}
	if !authorized {
		api.forbiddenError(w, "request not authorized")
		return
	}
}
```

2021-01-20 00:40 UTC, wwalexander commented on pkg/api/api_v0.go
> +	if !r.Context().Value(acylAPIKey).(bool) {
```
var authorized bool
key, ok := r.Context().Value(userAPIKey).(models.APIKey)
if ok && key.GitHubUser == qa.User {
    authorized = true
}
if !authorized {
    ...
}
```

is equivalent to

```
key, ok := r.Context().Value(userAPIKey).(models.APIKey)
authorized = ok && key.GitHubUser == qa.User
if !authorized {
    ...
}
```

is equivalent to 

```
key, ok := r.Context().Value(userAPIKey).(models.APIKey)
authorized = ok && key.GitHubUser == qa.User
if !(ok && key.GitHubUser == qa.User) {
    ...
}
```

is equivalent to 

```
key, ok := r.Context().Value(userAPIKey).(models.APIKey)
authorized = ok && key.GitHubUser == qa.User
if !ok || key.GitHubUser != qa.User {
    ...
}
```

(by De Morgans' theorem) so these should be the same. But it's a really minor nitpick and maybe it's less readable.

2021-01-20 00:43 UTC, wwalexander commented on pkg/api/api_v2.go
> +		w.WriteHeader(http.StatusInternalServerError)
True, the only side effect (besides that the client will only see a 200 status code) is that the default server seems to log a message about `superfluous response.WriteHeader call` when it happens but it doesn't seem to cause any actual issues.

2021-01-20 03:43 UTC, esterlinej commented on pkg/api/api_v0.go
> +	if !r.Context().Value(acylAPIKey).(bool) {
Okay, completely reworked. Single authorized apibase func, and more testing to check authorized/unauthorized for user api keys.

2021-01-20 03:44 UTC, esterlinej commented
@wwalexander Okay, completely reworked. Single authorized apibase func, and more testing to check authorized/unauthorized for user api keys.

2021-01-20 03:47 UTC, esterlinej commented on pkg/api/api_v2.go
> +		w.WriteHeader(http.StatusInternalServerError)
We'll talk in depth on this, make sure we're on the same page.

2021-01-20 03:48 UTC, esterlinej commented on pkg/api/api_v0.go
> +	if !r.Context().Value(acylAPIKey).(bool) {
See notes, completely reworked.

2021-01-20 21:13 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +		w.WriteHeader(http.StatusInternalServerError)
Good catch @wwalexander. Other handlers making the same error is not an excuse to continue doing it.

2021-01-20 22:17 UTC, bkeroackdsc requested changes

2021-01-20 22:17 UTC, bkeroackdsc commented on pkg/api/api.go
> +	if key, ok := ctx.Value(userAPIKey).(*models.APIKey); ok && key.GitHubUser == user {
Don't type assert twice. Get the value once from the context, then perform your logic.

2021-01-20 22:17 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +	userAPIKey   = "user_api_key"
These names should refer to context keys. The word "acyl" is redundant also. For example, `apiKeyCtxKey`.

I don't see why we need separate "user api" key and "api key" context keys.

2021-01-20 22:17 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +}
Don't let the user specify the UUID. We should generate a random one internally and then return it.

2021-01-20 22:17 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +		key.PermissionLevel = models.AdminPermission
Why are we using string integers query parameters? This would be better modeled with a field in the JSON request payload.

2021-01-20 22:17 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +	key.Name = r.URL.Query().Get("name")
Why a query param? You have a JSON request payload.

2021-01-20 22:17 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +					f(w, r.Clone(context.WithValue(r.Context(), userAPIKey, apikey)))
I don't think you need to have different context keys for "user" keys vs admin/root keys.

2021-01-20 22:17 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +	}()
This doesn't need to be asynchronous.

2021-01-20 22:17 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +		return
Why are you getting the UI session? This is unneeded.

2021-01-20 23:05 UTC, esterlinej commented on pkg/api/api_v2.go
> +		w.WriteHeader(http.StatusInternalServerError)
Will and I dug into this, it stems from an old issue with 1.11, and he confirmed it's not an issue in playground.

2021-01-20 23:06 UTC, esterlinej commented on pkg/api/middleware.go
> +	userAPIKey   = "user_api_key"
We need a way to check the root vs user key.

2021-01-20 23:21 UTC, esterlinej commented on pkg/api/middleware.go
> +	userAPIKey   = "user_api_key"
Didn't realize I could simply piggyback off the same key at the time.

2021-01-22 19:18 UTC, esterlinej commented on pkg/api/api_v2.go
> +}
They don't specify the key, this is the return object only

2021-01-22 19:19 UTC, esterlinej commented on pkg/api/api_v2.go
> +		return
This was to confirm the user in session making the request to create/get/destroy the key

2021-01-22 21:45 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +	userAPIKey   = "user_api_key"
One context key should always map to one data structure in the context. You can then use fields within that data structure in your logic.

2021-01-22 21:46 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +}
Use different struct types for the request and response schemas.

2021-01-22 23:00 UTC, esterlinej commented on pkg/api/api_v2.go
> +}
I see, the naming is confusing, sorry, will update this.

2021-01-26 18:41 UTC, esterlinej commented on pkg/api/middleware.go
> +		user := r.URL.Query().Get("user")
The `env/_search/` endpoints will reject forbidden 403 if a user api key is used without searching with their own name, I think we should handle this gracefully rather. Thoughts?

2021-01-26 18:44 UTC, esterlinej commented on pkg/api/api_v0.go
>  	// DEPRECATED: no longer supported, please use /v0/envs/_search
Deprecated endpoints that go through tokenAuth are not updated with this PR, and provide end-arounds to access the data. I recommend we remove these deprecated endpoints rather than provide support.

2021-01-26 19:19 UTC, bkeroackdsc requested changes

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +	el := r.Context().Value(dataCtx).(*models.EventLog)
Value not pointer. Use a different context key.

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +type v2UserAPIKeyCreate struct {
Name these types to indicate if they are request or response structs.

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +		w.WriteHeader(http.StatusInternalServerError)
This should be 403 Bad Request

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +	User        string `json:"user"`
Don't allow the client to specify user. User should be inferred by the credentials used to authorize the API call.

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +	if key.Permission < models.MinPermissionLevel || key.Permission > models.MaxPermissionLevel {
You may want to explicitly check for `key.Permission < 0` (since the field is a signed integer).

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +	Token       uuid.UUID              `json:"token"`
Never return the actual token. That should be displayed to the user once on creation and then never again.

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +	User        string                 `json:"user"`
The user should be inferred by the credentials used to authorize this API call. We can have a separate API endpoint authorized by root API tokens which allows displaying all API tokens (or by user, etc). I'm not sure if we need that yet however.

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +	}
Always perform security/authorization checks as early as possible in the handler. This can be put before you query for keys by user.

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +	v2uaks := []V2UserAPIKey{}
Since you know the length of `apikeys` you can initialize this with a size: `v2uaks := make([]V2UserAPIKey, len(apikeys))`

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +func (api *v2api) apiKeyByIdHandler(w http.ResponseWriter, r *http.Request) {
I don't think we need this endpoint.

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +		qa, err := ra.dl.GetQAEnvironmentConsistently(r.Context(), el.EnvName)
There's no difference between `GetQAEnvironmentConsistently()` and `GetQAEnvironment()`. This is tech debt from when DynamoDB was used.

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +func (ra reqAuthorizor) authorizedEnv(f http.HandlerFunc) http.HandlerFunc {
Document these middleware methods both with what they do, and also the assumptions/expectations they have. For example, they assume that `tokenAuth()` middleware is used prior to them in the chain and will fail if that isn't the case.

2021-01-26 19:19 UTC, bkeroackdsc commented on pkg/persistence/pg.go
> +	return p.collectRows(p.db.QueryContext(ctx, `SELECT `+models.QAEnvironment{}.Columns()+` from qa_environments WHERE username = $1 AND `+fmt.Sprintf(`created >= (current_timestamp - interval '%v days
You're missing a `LIMIT` clause (using the n method parameter).

2021-01-26 19:20 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +		user := r.URL.Query().Get("user")
I would implement a new datalayer method `SearchEnvsForUser` which adds a mandatory user to the search parameters.

2021-01-26 20:07 UTC, esterlinej commented on pkg/api/api_v0.go
> +	qa := r.Context().Value(dataCtx).(*models.QAEnvironment)
I will try again, but wasn't working until I made this a pointer

2021-01-26 20:41 UTC, esterlinej commented on pkg/api/api_v2.go
> +	User        string                 `json:"user"`
Makes sense, I was thinking about this through more from a user controlled "I need a token to do x with these permissions" but if they don't have those permissions to begin with, then this breaks

2021-01-26 20:53 UTC, esterlinej commented on pkg/api/api_v2.go
> +	}
Won't be able to move this up, I removed user from the field and forgot to clean it up out of the handler. The only user we have is the `uis.GitHubUser` prior to fetching the key, then confirming that the user on the key id matches.

2021-01-26 21:10 UTC, esterlinej commented on pkg/persistence/pg.go
> +	return p.collectRows(p.db.QueryContext(ctx, `SELECT `+models.QAEnvironment{}.Columns()+` from qa_environments WHERE username = $1 AND `+fmt.Sprintf(`created >= (current_timestamp - interval '%v days
Looking into this, I duplicated the existing method without user, and searched options to confirm this was still the right way to do this, and didn't have `LIMIT` included:
https://stackoverflow.com/questions/5465484/how-to-list-records-with-date-from-the-last-10-days

2021-01-26 23:02 UTC, esterlinej commented on pkg/api/api_v2.go
> +	User        string                 `json:"user"`
I'm now pulling user from the session

2021-01-26 23:03 UTC, esterlinej commented on pkg/api/api_v0.go
> +	qa := r.Context().Value(dataCtx).(*models.QAEnvironment)
I'll add nil checks, cause the bigger issue is we have to then convert this to a copy, then convert it back to a pointer for the handler to use.

2021-01-28 01:04 UTC, esterlinej commented
We may want/need to add a delete key by name, in case we need to cleanup keys without ids?

2021-01-28 21:07 UTC, esterlinej commented on pkg/persistence/pg.go
> +	return p.collectRows(p.db.QueryContext(ctx, `SELECT `+models.QAEnvironment{}.Columns()+` from qa_environments WHERE username = $1 AND `+fmt.Sprintf(`created >= (current_timestamp - interval '%v days
Resolving per our conversation

2021-01-28 23:32 UTC, bkeroackdsc requested changes

2021-01-28 23:32 UTC, bkeroackdsc commented on pkg/api/api_v0.go
> +	if user == acylKey {
Instead of using a string constant as a sentinel to indicate that the API key is an admin key, instead store a struct in the context with a "IsAdmin" boolean field.

2021-01-28 23:32 UTC, bkeroackdsc commented on pkg/api/api_v0.go
> +	output := v0QAEnvironmentFromQAEnvironment(qap)
You don't need the additional named variable `qap`. Do `output := v0QAEnvironmentFromQAEnvironment(&qa)` instead

2021-01-28 23:32 UTC, bkeroackdsc commented on pkg/api/api_v0.go
> +		api.internalError(w, fmt.Errorf("error authorize context failed"))
Use a more informative error message. Something like `fmt.Errorf("unexpected qa env type from context: %T", qa)`

2021-01-28 23:32 UTC, bkeroackdsc commented on pkg/api/api_v0.go
> +	userSearch, ok := r.Context().Value(searchCtxKey).(bool)
Use the same mechanism here as you use above for determining if this is a user api key or an admin key.

2021-01-28 23:32 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +	apiKeyCtxKey   = "api_key"     // bool or models.APIKey
A context key must always map to exactly one data type. Don't overload it (bool and models.APIKey).

2021-01-28 23:32 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +	dl      persistence.DataLayer
What's the reasoning behind making this field private?

2021-01-28 23:32 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +		}
You can put this outside of the closure to avoid allocating a new anonymous function for every handler request.

2021-01-28 23:32 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +func (ra reqAuthorizor) authorizedSearch(f http.HandlerFunc) http.HandlerFunc {
It doesn't appear that there's anything specific to search for this middleware, so it should be renamed to something more descriptive.

2021-01-28 23:32 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +func (ra reqAuthorizor) authorizedUser(f http.HandlerFunc) http.HandlerFunc {
The logic in `authorizedUser()` and `authorizedSearch()` seem to be the same. Combine and rename.

2021-01-28 23:32 UTC, bkeroackdsc commented on pkg/persistence/pg.go
> +func (p *PGLayer) SearchEnvsForUser(ctx context.Context, opts models.EnvSearchParameters) ([]QAEnvironment, error) {
Don't copy/paste the entire SearchEnvs method logic. Just add the user parameter and then call SearchEnvs.

2021-01-28 23:41 UTC, esterlinej commented on pkg/api/middleware.go
> +	apiKeyCtxKey   = "api_key"     // bool or models.APIKey
I had them separate prior and you asked me to combine them. I will revert this change.

2021-01-28 23:44 UTC, esterlinej commented on pkg/api/middleware.go
> +	dl      persistence.DataLayer
My thought behind this is limiting it's scope to the api package.

2021-01-28 23:45 UTC, esterlinej commented on pkg/api/middleware.go
> +func (ra reqAuthorizor) authorizedSearch(f http.HandlerFunc) http.HandlerFunc {
True, I refactored this, but didn't alter the name, even though its more generic than before.

2021-01-28 23:46 UTC, esterlinej commented on pkg/api/middleware.go
> +func (ra reqAuthorizor) authorizedUser(f http.HandlerFunc) http.HandlerFunc {
One returns a string, the other a bool. Let me see what I can do.

2021-01-28 23:48 UTC, esterlinej commented on pkg/api/api_v0.go
> +	if user == acylKey {
Ha, I did this at first and then thought I was over-engineering it that way.

2021-01-29 00:53 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +	apiKeyCtxKey   = "api_key"     // bool or models.APIKey
I would never ask you to overload a context key with multiple types. You must've misunderstood.

2021-01-29 00:53 UTC, bkeroackdsc commented on pkg/api/api_v0.go
> +	if user == acylKey {
Actually APIKey has a PermissionLevel field you can use to determine if it's admin or not
https://github.com/dollarshaveclub/acyl/blob/3e2477a8df5379239057a29050ffb23f6b476b84/pkg/models/apikeys.go#L16

2021-01-29 04:08 UTC, esterlinej commented on pkg/api/api_v0.go
> +	if user == acylKey {
Sure, though that currently is configurable, and `IsAdmin` to me is about is this a root key vs user key

2021-01-29 18:17 UTC, esterlinej commented on pkg/api/api_v0.go
> +	if user == acylKey {
Added in the `authenticated()` function

2021-01-30 01:54 UTC, wwalexander commented on pkg/api/api_v2.go
> +	j, err := json.Marshal(v2EventLogFromEventLog(elp))
Could be shortened to just
`j, err := json.Marshal(v2eventLogFromEventLog(&el))`

2021-01-30 02:06 UTC, wwalexander commented on pkg/persistence/pg.go
> +	return p.collectRows(p.db.QueryContext(ctx, `SELECT `+models.QAEnvironment{}.Columns()+` from qa_environments WHERE username = $1 AND `+fmt.Sprintf(`created >= (current_timestamp - interval '%v days
While I don't think this particular usage of fmt.Sprintf inside a SQL string could lead to injection, we should probably avoid doing it wherever possible. In this case, you can create an interval from a query parameter like:

    return p.collectRows(p.db.QueryContext(ctx, `SELECT `+models.QAEnvironment{}.Columns()+` from qa_environments WHERE username = $1 AND created >= (current_timestamp - make_interval(days := $2)) ORDER BY created DESC;`, user, n))

2021-01-30 02:07 UTC, wwalexander approved these changes
LGTM, besides the couple of minor improvements I suggested.

2021-01-30 18:43 UTC, esterlinej commented on pkg/api/api_v2.go
> +	j, err := json.Marshal(v2EventLogFromEventLog(elp))
Good catch, missed removing this

2021-01-30 18:43 UTC, esterlinej commented on pkg/persistence/pg.go
> +	return p.collectRows(p.db.QueryContext(ctx, `SELECT `+models.QAEnvironment{}.Columns()+` from qa_environments WHERE username = $1 AND `+fmt.Sprintf(`created >= (current_timestamp - interval '%v days
Thanks, will change

2021-02-02 22:43 UTC, esterlinej commented
The best way I found to do this, have `tokenAuth` write `Authenticated` to the `apiKeyCtxKey` Context, removing the need to the other two, along with the `authenticated()` function, and have each authorizor function get that context to confirm against the Authenticated root key / admin or user.

2021-02-02 22:51 UTC, esterlinej commented
Updated PR Description

2021-02-02 22:55 UTC, esterlinej commented
Change applied to simplify, but I'm still reviewing to make certain I understand your concerns.

To add, the first `tokenAuth()` simply checks the token is either a valid root or user key, but doesn't otherwise check for authorization, which is where the authorizor functions come into effect. They then ensure the request is authorized before proceeding to the handler.

2021-02-03 00:28 UTC, esterlinej commented
Even more simplification, if root admin key is used, it inserts `models.APIKey{PermissionLevel: models.AdminPermission}` into the `apiKeyCtxKey`, otherwise if user it inserts that User API Key

2021-02-03 17:39 UTC, bkeroackdsc requested changes

2021-02-03 17:39 UTC, bkeroackdsc commented on pkg/models/apikeys.go
> +	MaxPermissionLevel = 3
Never rely on the internal literal values of enums since it's an implementation detail of the compiler. Regardless of that, this is unneeded. Use the symbolic constant names instead.

2021-02-03 17:39 UTC, bkeroackdsc commented on pkg/persistence/pg.go
> +	days := fmt.Sprintf(`created >= (current_timestamp - interval '%v days')`, n)
This is a (very remote) SQL injection vulnerability. Never use Sprintf to create SQL queries, always use query placeholders ("$1", "$2"...). For this, use an additional query placeholder in the line below.

2021-02-03 18:34 UTC, esterlinej commented on pkg/models/apikeys.go
> +	MaxPermissionLevel = 3
Understood. I forgot to remove this from a prior refactor.

2021-02-03 20:45 UTC, esterlinej commented on pkg/persistence/pg.go
> +	days := fmt.Sprintf(`created >= (current_timestamp - interval '%v days')`, n)
Unfortunately I was not able to find a better solution since this is wrapped within a string literal, and must be resolved prior. The only real protection is that it's using the `uint`, though I understand the concern.

2021-02-04 00:00 UTC, bkeroackdsc requested changes
A few small changes I missed in last CR, but otherwise it's looking good.

2021-02-04 00:00 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +		}
If the APIKey isn't found in the context, abort and return a 403 unauthorized to the client.

```go
ak, ok := r.Context().Value(apiKeyCtxKey).(models.APIKey)
if !ok || ak.User == "" {
   w.WriteHeader(http.StatusForbidden)
   return
}
```

2021-02-04 00:00 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +		}
Same here. If APIKey isn't found in the context, return a 403 to the client.

2021-02-04 00:00 UTC, bkeroackdsc commented on pkg/api/middleware.go
> +		}
Same here. Return 403 if APIKey isn't found.

2021-02-04 00:48 UTC, esterlinej commented on pkg/api/middleware.go
> +		}
Adding this to the first thing checked within the middleware handler function

2021-02-04 00:48 UTC, esterlinej commented on pkg/api/middleware.go
> +		}
Adding this to the first thing checked within the middleware handler function

2021-02-04 00:49 UTC, esterlinej commented on pkg/api/middleware.go
> +		}
Adding this to the first thing checked within the middleware handler function, but cannot include user, because when we forward the root key, no user exists.

2021-02-04 17:44 UTC, bkeroackdsc approved these changes

2021-02-05 01:01 UTC, merged