User API Token UI
dollarshaveclub/acyl pull request #154
Opened 2021-03-19 00:17 UTC by esterlinej

### Implement User API Token UI 
- Add stub for User Settings page
 - Add link to User Settings page in user dropdown menu in header
 - Add API UI handler & path support
 - Add API v2 functions & tests for:
   - GET /v2/user/tokens
   - POST /v2/user/token
   - DELETE /v2/user/token/{id}

2021-04-13 19:05 UTC, esterlinej commented
Looking for suggestions on the API Documents help icon (anchored to the API Keys upper right bar), possibly make it into its own group with verbiage, as it doesn't necessarily belong in the API Keys heading group, but did this to keep things compact.

2021-04-13 22:25 UTC, bkeroackdsc requested changes

2021-04-13 22:25 UTC, bkeroackdsc commented on pkg/persistence/apikeys.go
> +		LastUsed:        pq.NullTime{Time: time.Time{}, Valid: false},
If you omit this field it will do the same thing, since the zero value for `pq.NullTime` would have those values (zero value time.TIme, false).

2021-04-13 22:25 UTC, bkeroackdsc commented on ui/assets/user.js
> +    console.log("DEBUG:: showHideAPIKeysCreateNew");
debug console.log

2021-04-13 22:25 UTC, bkeroackdsc commented on ui/assets/user.js
> +    console.log("DEBUG:: setAPIKeys");
debug console.log

2021-04-13 22:25 UTC, bkeroackdsc commented on ui/assets/user.js
> +    console.log("DEBUG:: renderCardHeader");
debug console.log

2021-04-13 22:25 UTC, bkeroackdsc commented on ui/assets/user.js
> +    console.log("DEBUG:: renderCardBodyTableBodyRow");
debug console.log

2021-04-13 22:25 UTC, bkeroackdsc commented on ui/assets/user.js
> +    console.log("DEBUG:: permissionLevel");
debug console.log

2021-04-13 23:32 UTC, esterlinej commented on pkg/api/api_v2.go
> +	if reqParams.Permission < 0 || reqParams.Permission < models.MinPermissionLevel || reqParams.Permission > models.MaxPermissionLevel {
Yes, thank you for reminding me, I meant to ask if we should be blocking Admin key creation at the API level, or enforce admin key `/user/token/admin` to require a root key to process that request. But that being the case why not just use the root key.

2021-04-23 18:47 UTC, bkeroackdsc requested changes

2021-04-23 18:47 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +	Permission  int    `json:"permission"`
This should be the constant type, not a bare integer.

https://github.com/dollarshaveclub/acyl/blob/1c0c673d131ffb3cabc456154c2508df9b31d135/pkg/models/apikeys.go#L49

2021-04-23 18:47 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +		w.WriteHeader(http.StatusInternalServerError)
This should be a 403 Bad Request response code.

2021-04-23 18:47 UTC, bkeroackdsc commented on pkg/api/api_v2.go
> +		api.logger.Printf("error deleting user token: %v: %v", id, err)
You probably should return a 500 error here.

2021-04-23 18:47 UTC, bkeroackdsc commented on pkg/models/apikeys.go
> +)
These should be defined in the API package, and should be named like `MinAPIKeyPermissionLevel` etc.

2021-04-23 18:47 UTC, bkeroackdsc commented on ui/assets/user.js
> +    if (!document.getElementById("apiKeysBody").hasChildNodes()) {
For readability, it's preferred to have a positive condition first.

Instead of `if (!foo) { a } else { b }` it's better to do the equivalent: `if (foo) { b } else { a }`.

2021-04-23 18:47 UTC, bkeroackdsc commented on ui/assets/user.js
> +    return level;
```javascript
if (permission === "Write") {
   return 2;
}
return 1;
```

2021-04-23 18:47 UTC, bkeroackdsc commented on ui/assets/user.js
> +        console.log(`DEBUG: apiKeyObj: ${apiKeyObj.description}`)
Debug printf

2021-04-23 18:47 UTC, bkeroackdsc commented on ui/assets/user.js
> +            console.log(`user tokens request failed: ${req.status}: ${req.responseText}`);
missing a return

2021-04-23 20:52 UTC, bkeroackdsc approved these changes

2021-04-23 23:21 UTC, merged