Upgrade to Helm 3
dollarshaveclub/acyl pull request #160
Opened 2021-06-09 19:55 UTC by esterlinej

### Features & Upgrades
- update modules
- update acyl metahelm package
- remove support for Tiller
- update commands with tiller integration

2021-07-09 22:48 UTC, bkeroackdsc commented
@esterlinej  You're on the right track but I don't think you can share a `metahelm.Manager` as a field on ChartInstaller.

`metahelm.Manager` is threadsafe, but it contains an embedded `*action.Configuration` which should be customized to a specific environment as it's being built. Specifically, each time a new namespace is created, acyl needs to create a new `*action.Configuration` with the namespace and driver info, and then must run `cfg.Init(...)` on that configuration before creating a new `metahelm.Manager` and then using that to install/upgrade all the charts for the environment.

The way I would approach this is instead of having a literal `*metahelm.Manager` field on the ChartInstaller struct, instead have something like:
```go
type ChartInstaller struct {
// ...
  mhmf     func(...) *metahelm.Manager
// ...
}
```
In the constructor when you create a ChartInstaller, you can inject in a function that either creates a real manager or a mock one or whatever you need.

In recent Helm v3 versions, `cfg.Init()` (on `*action.Configuration`) is [threadsafe](https://github.com/helm/helm/issues/9089), so when a new environment is being built, after the namespace has been created and set up, ChartInstaller will need to run something like `cfg.Init(kc, "nitro-9999-my-namespace", <driver name>, nil)`.

2021-07-20 17:18 UTC, esterlinej commented
Even though we're defining the kubernetes namespace (`metahelm.WithK8sNamespace(namespace)`), and Acyl creating the namespace per usual, metahelm appears not to be respecting that namespace, or at least not setting it within the generated the context for the `*action.Configuration`.

I found a way to enforce this within Acyl, but wondering if this shouldn't be automatically handled at the metahelm package itself, than forcing it from Acyl, since we already provide the namespace to metahelm in the initialization. I'll continue to investigate, and hopefully find a better solution, though what I have currently is now installing the charts into the expected namespace.

2021-07-28 16:32 UTC, esterlinej commented
TODO:
- Official Metahelm Helm3 (3.6.0) build, updating Acyl module dependency
- Thorough Functional Testing QAEs (Create, Update, Destroy)
- Deployment Strategy, possibly move DB changes & migration to it's own branch

2021-08-04 20:41 UTC, esterlinej commented
Running functional tests, but this is basically code complete, and ready for official review.

2021-08-04 20:42 UTC, bkeroackdsc requested changes

2021-08-04 20:42 UTC, bkeroackdsc commented on pkg/nitro/metahelm/metahelm.go
> +	if mhm == nil {
Add this to the previous conditional: `if err != nil || mhm == nil { ... }`

2021-08-04 22:25 UTC, bkeroackdsc approved these changes

2021-09-14 17:21 UTC, merged